version: '3'
services:
  # FastAPI Application
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - postgres-db
    env_file:
      - .env
    volumes:
      - ./app:/app/app

  # PostgreSQL Database
  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: nasa_backend
      POSTGRES_PASSWORD: nasa_backend
      POSTGRES_DB: mydatabase
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - '45432:5432'
